# Generated by Django 4.2 on 2023-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details_Model',
            fields=[
                ('Student_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.TextField(max_length=50)),
                ('Student_Age', models.IntegerField(null=True)),
                ('Student_Email', models.EmailField(max_length=100)),
                ('Student_Phone_Number', models.TextField(max_length=10)),
                ('Student_RollNumber', models.TextField(max_length=20)),
                ('Student_Address', models.TextField(max_length=200)),
                ('Student_Branch', models.TextField(max_length=10)),
                ('Student_Section', models.TextField(max_length=4)),
                ('Student_Gender', models.TextField(max_length=10)),
                ('Student_Profile', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
