# Generated by Django 4.2 on 2023-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Branch',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Gender',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Phone_Number',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_RollNumber',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Section',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
