# Generated by Django 4.2 on 2023-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_alter_student_details_model_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Profile',
            field=models.FileField(upload_to='images'),
        ),
    ]
