# Generated by Django 4.2 on 2023-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_student_details_model_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Profile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
