# Generated by Django 4.2 on 2023-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_alter_student_details_model_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Profile',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
