# Generated by Django 4.2 on 2023-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_alter_student_details_model_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Details_Model',
            fields=[
                ('Class_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Class_Incharge_Name', models.TextField(max_length=50)),
                ('Branch_Name', models.TextField(max_length=20)),
                ('Section', models.TextField(max_length=10)),
                ('Class_Start_Time', models.TimeField()),
                ('Class_Duration', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'class_details',
            },
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Profile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
