# Generated by Django 4.2 on 2023-04-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0008_class_details_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Floor_Number',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Room_Number',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
