# Generated by Django 4.2 on 2023-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0009_class_details_model_class_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Class_Start_Time',
            field=models.TimeField(null=True),
        ),
    ]
