# Generated by Django 4.2 on 2023-04-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0010_alter_class_details_model_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Password',
            field=models.IntegerField(null=True),
        ),
    ]
