# Generated by Django 4.2 on 2023-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0011_student_details_model_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Subject_Name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
