# Generated by Django 4.2 on 2023-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0012_class_details_model_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_End_Time',
            field=models.TimeField(null=True),
        ),
    ]
