# Generated by Django 4.2 on 2023-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0013_class_details_model_class_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Last_Login_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Last_Login_Time',
            field=models.TimeField(null=True),
        ),
    ]
