# Generated by Django 4.2 on 2023-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0014_student_details_model_student_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_No_Of_Times_Login',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
