# Generated by Django 4.2 on 2023-04-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0015_student_details_model_student_no_of_times_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_No_Of_Times_Logout',
            field=models.TimeField(null=True),
        ),
    ]
