# Generated by Django 4.2 on 2023-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0016_student_details_model_student_no_of_times_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_No_Of_Times_Logout',
            field=models.TimeField(default=0, null=True),
        ),
    ]
