# Generated by Django 4.2 on 2023-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0018_alter_student_details_model_student_no_of_times_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Online_Status',
            field=models.TextField(default='offline'),
        ),
    ]
