# Generated by Django 4.2 on 2023-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0019_student_details_model_student_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Password',
            field=models.TextField(null=True),
        ),
    ]
