# Generated by Django 4.2 on 2023-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0020_alter_student_details_model_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_QR_Code',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
