# Generated by Django 4.2 on 2023-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0022_alter_class_details_model_class_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Class_QR_Code',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
