# Generated by Django 4.2 on 2023-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0025_alter_class_details_model_class_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Upload_QR_Codes',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
