# Generated by Django 4.2 on 2023-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0026_student_details_model_student_upload_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Upload_QR_Codes',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
