# Generated by Django 4.2 on 2023-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0027_alter_student_details_model_student_upload_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_QR_Status',
            field=models.TextField(default='deactive'),
        ),
    ]
