# Generated by Django 4.2 on 2023-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0028_class_details_model_class_qr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Upload_QR_Codes',
            field=models.FileField(null=True, upload_to='qr_images/'),
        ),
    ]
