# Generated by Django 4.2 on 2023-04-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0029_alter_student_details_model_student_upload_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Class_Subject',
            field=models.TextField(null=True),
        ),
    ]
