# Generated by Django 4.2 on 2023-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0033_alter_class_details_model_class_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Class_QR_Code',
            field=models.FileField(null=True, upload_to='images/cla_qr'),
        ),
        migrations.AlterField(
            model_name='student_details_model',
            name='Student_Upload_QR_Codes',
            field=models.FileField(null=True, upload_to='images/stu_qr'),
        ),
    ]
