# Generated by Django 4.2 on 2023-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0038_alter_class_details_model_class_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Class_QR_Code',
            field=models.FileField(null=True, upload_to='media/images/cla_qr/'),
        ),
    ]
