# Generated by Django 4.2 on 2023-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0045_alter_class_details_model_class_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_QR_Code_Upload_TIme',
            field=models.TimeField(null=True),
        ),
    ]
