# Generated by Django 4.2 on 2023-04-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0046_student_details_model_student_qr_code_upload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details_model',
            old_name='Student_QR_Code_Upload_TIme',
            new_name='Student_QR_Code_Upload_Time',
        ),
    ]
