# Generated by Django 4.2 on 2023-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0047_rename_student_qr_code_upload_time_student_details_model_student_qr_code_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Date',
            field=models.DateField(null=True),
        ),
    ]
