# Generated by Django 4.2 on 2023-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0048_class_details_model_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_QR_Code_Upload_Date',
            field=models.DateField(null=True),
        ),
    ]
