# Generated by Django 4.2 on 2023-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0049_student_details_model_student_qr_code_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_QR_Status',
            field=models.TextField(default='not-uploaded'),
        ),
    ]
