# Generated by Django 4.2 on 2023-04-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0050_student_details_model_student_qr_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Details_Model',
        ),
    ]
