# Generated by Django 4.2 on 2023-04-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0051_delete_student_details_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details_Model',
            fields=[
                ('Student_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.TextField(max_length=50)),
                ('Student_Age', models.IntegerField(null=True)),
                ('Student_Email', models.EmailField(max_length=100)),
                ('Student_Phone_Number', models.TextField(max_length=10, null=True)),
                ('Student_RollNumber', models.TextField(max_length=20, null=True)),
                ('Student_Address', models.TextField(max_length=200, null=True)),
                ('Student_Branch', models.TextField(max_length=10, null=True)),
                ('Student_Section', models.TextField(max_length=4, null=True)),
                ('Student_Gender', models.TextField(max_length=10, null=True)),
                ('Student_Profile', models.FileField(upload_to='images/')),
                ('Student_Status', models.TextField(default='pending')),
                ('Student_Password', models.TextField(null=True)),
                ('Student_Last_Login_Time', models.TimeField(null=True)),
                ('Student_Last_Login_Date', models.DateField(null=True)),
                ('Student_No_Of_Times_Login', models.IntegerField(default=0, null=True)),
                ('Student_No_Of_Times_Logout', models.IntegerField(default=0, null=True)),
                ('Student_Online_Status', models.TextField(default='offline')),
                ('Student_Upload_QR_Codes', models.FileField(null=True, upload_to='images/stu_qr/')),
                ('Class_Subject', models.TextField(null=True)),
                ('Student_QR_Code_Upload_Time', models.TimeField(null=True)),
                ('Student_QR_Code_Upload_Date', models.DateField(null=True)),
                ('Student_QR_Status', models.TextField(default='not-uploaded')),
                ('Class_Details_Foregin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.class_details_model')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
