# Generated by Django 4.2 on 2023-04-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0052_student_details_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details_model',
            name='Class_Details_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.class_details_model'),
        ),
    ]
