# Generated by Django 4.2 on 2023-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0053_alter_student_details_model_class_details_foregin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details_model',
            name='Class_Details_Foregin',
        ),
        migrations.DeleteModel(
            name='Class_Details_Model',
        ),
    ]
