# Generated by Django 4.2 on 2023-04-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0054_remove_student_details_model_class_details_foregin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Details_Model',
            fields=[
                ('Class_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Class_Incharge_Name', models.TextField(max_length=50)),
                ('Subject_Name', models.TextField(max_length=20, null=True)),
                ('Branch_Name', models.TextField(max_length=20)),
                ('Section', models.TextField(max_length=10)),
                ('Class_Start_Time', models.TimeField(null=True)),
                ('Class_End_Time', models.TimeField(null=True)),
                ('Class_Duration', models.TextField(max_length=20)),
                ('Class_Floor_Number', models.TextField(max_length=10, null=True)),
                ('Class_Room_Number', models.TextField(max_length=10, null=True)),
                ('Class_Latitude', models.FloatField(null=True)),
                ('Class_Longitude', models.FloatField(null=True)),
                ('Class_QR_Code', models.FileField(null=True, upload_to='images/cla_qr/')),
                ('Class_QR_Status', models.TextField(default='deactive')),
                ('Class_Date', models.DateField(null=True)),
                ('Student_Details_Foregin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model')),
            ],
            options={
                'db_table': 'class_details',
            },
        ),
    ]
