# Generated by Django 4.2 on 2023-04-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0055_class_details_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Student_Details_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model'),
        ),
    ]
