# Generated by Django 4.2 on 2023-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0056_alter_class_details_model_student_details_foregin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='QR_Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='QR_Longitude',
            field=models.FloatField(null=True),
        ),
    ]
