# Generated by Django 4.2 on 2023-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0057_student_details_model_qr_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Last_Logout_Time',
            field=models.TimeField(null=True),
        ),
    ]
