# Generated by Django 4.2 on 2023-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0058_student_details_model_student_last_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Att_Chemistry',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Att_Django',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Att_Maths',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Att_Physics',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Att_Python',
            field=models.TextField(default='absent'),
        ),
    ]
