# Generated by Django 4.2 on 2023-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0059_student_details_model_att_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Att_English',
            field=models.TextField(default='absent'),
        ),
    ]
