# Generated by Django 4.2 on 2023-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0060_student_details_model_att_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Details_Model',
            fields=[
                ('Stu_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.TextField(max_length=50)),
                ('Student_Branch', models.TextField(max_length=50)),
                ('Student_Subject', models.TextField(max_length=100)),
                ('Student_Section', models.TextField(max_length=20)),
                ('Student_Rollnum', models.TextField(max_length=20)),
                ('Att_Date', models.DateField(null=True)),
                ('Att_Status', models.TextField(default='present')),
            ],
            options={
                'db_table': 'attendance_details',
            },
        ),
    ]
