# Generated by Django 4.2 on 2023-04-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0061_attendance_details_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_details_model',
            old_name='Stu_Id',
            new_name='Att_Id',
        ),
        migrations.AddField(
            model_name='attendance_details_model',
            name='Stu_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model'),
        ),
        migrations.AlterField(
            model_name='attendance_details_model',
            name='Att_Status',
            field=models.TextField(default='absent'),
        ),
    ]
