# Generated by Django 4.2 on 2023-04-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0062_rename_stu_id_attendance_details_model_att_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='Cla_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.class_details_model'),
        ),
    ]
