# Generated by Django 4.2 on 2023-04-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0064_alter_class_details_model_student_details_foregin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_details_model',
            name='Student_Details_Foregin',
        ),
    ]
