# Generated by Django 4.2 on 2023-04-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0066_class_details_model_student_details_foregin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Student_Details_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_in_class', to='teacherapp.student_details_model'),
        ),
    ]
