# Generated by Django 4.2 on 2023-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0069_class_details_model_student_details_foregin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Cpu',
            field=models.TextField(null=True),
        ),
    ]
