# Generated by Django 4.2 on 2023-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0070_student_details_model_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details_model',
            name='Cpu',
        ),
        migrations.AddField(
            model_name='attendance_details_model',
            name='Cpu',
            field=models.TextField(null=True),
        ),
    ]
