# Generated by Django 4.2 on 2023-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0071_remove_student_details_model_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='Ram',
            field=models.TextField(null=True),
        ),
    ]
