# Generated by Django 4.2 on 2023-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0072_attendance_details_model_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='HardDisk',
            field=models.TextField(null=True),
        ),
    ]
