# Generated by Django 4.2 on 2023-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0073_attendance_details_model_harddisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Count',
            field=models.IntegerField(null=True),
        ),
    ]
