# Generated by Django 4.2 on 2023-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0074_class_details_model_class_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details_model',
            name='Class_Count',
            field=models.IntegerField(default=0),
        ),
    ]
