# Generated by Django 4.2 on 2023-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0075_alter_class_details_model_class_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='Class_Incharge',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
