# Generated by Django 4.2 on 2023-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0077_alter_attendance_details_model_class_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='Class_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance_details_model',
            name='Class_Incharge',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
