# Generated by Django 4.2 on 2023-04-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0078_attendance_details_model_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_details_model',
            name='QR_Time',
            field=models.TimeField(null=True),
        ),
    ]
