# Generated by Django 4.2 on 2023-04-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0079_attendance_details_model_qr_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Coducted_Model',
            fields=[
                ('Cla_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Branch', models.TextField(max_length=50)),
                ('Section', models.TextField(max_length=50)),
                ('Subject', models.TextField(max_length=50)),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField(null=True)),
                ('Cla_Foregin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.class_details_model')),
                ('Stu_Foregin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model')),
            ],
            options={
                'db_table': 'classes_conduct',
            },
        ),
    ]
