# Generated by Django 4.2 on 2023-04-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0080_classes_coducted_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_coducted_model',
            name='Stu_Foregin',
        ),
    ]
