# Generated by Django 4.2 on 2023-04-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0081_remove_classes_coducted_model_stu_foregin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_coducted_model',
            name='Class_Inch',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
