# Generated by Django 4.2 on 2023-04-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0082_classes_coducted_model_class_inch'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_coducted_model',
            name='Atten_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.attendance_details_model'),
        ),
        migrations.AddField(
            model_name='classes_coducted_model',
            name='Stu_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model'),
        ),
    ]
