# Generated by Django 4.2 on 2023-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0083_classes_coducted_model_atten_foregin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Class_Date',
            field=models.DateField(null=True),
        ),
    ]
