# Generated by Django 4.2 on 2023-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0084_student_details_model_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_Chemistry',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_Django',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_English',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_Maths',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_Physics',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='Att_Python',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='QR_Latitude',
        ),
        migrations.RemoveField(
            model_name='student_details_model',
            name='QR_Longitude',
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Class_Inch_Name',
            field=models.TextField(null=True),
        ),
    ]
