# Generated by Django 4.2 on 2023-04-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0085_remove_student_details_model_att_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Class_Time',
            field=models.TimeField(null=True),
        ),
    ]
