# Generated by Django 4.2 on 2023-05-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0086_student_details_model_class_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes_Coducted_Model',
        ),
    ]
