# Generated by Django 4.2 on 2023-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0087_delete_classes_coducted_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student_details_model',
            name='Student_Longitude',
            field=models.FloatField(null=True),
        ),
    ]
