# Generated by Django 4.2 on 2023-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0088_student_details_model_student_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_details_model',
            name='Class_Status',
            field=models.TextField(default='deactive'),
        ),
    ]
