# Generated by Django 4.2 on 2023-05-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0089_class_details_model_class_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_details_model',
            name='Class_Status',
        ),
    ]
