# Generated by Django 4.2 on 2023-05-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0090_remove_class_details_model_class_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Coducted_Model',
            fields=[
                ('Cla_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Class_Inch', models.TextField(max_length=100, null=True)),
                ('Branch', models.TextField(max_length=50)),
                ('Section', models.TextField(max_length=50)),
                ('Subject', models.TextField(max_length=100)),
                ('Cl_Date', models.DateField(null=True)),
                ('Cl_Time', models.TimeField(null=True)),
                ('Atten_Foregin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.attendance_details_model')),
                ('Cla_Foregin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.class_details_model')),
                ('Stu_Foregin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.student_details_model')),
            ],
            options={
                'db_table': 'classes_conduct',
            },
        ),
    ]
